### ISSUE TITLE
Peer tp Peer code review

### ISSUE THREAD

**Issue by thankgodr** [thankgodr/capstone-js-project#29]

**Comment by HevarKas** [comment]
good job 👍🏻

**Comment by jellywiz** [comment]
### Well done with the project 🔥

**It looks great**

- Using API ✔️
- Best JavaScript Practice ✔️
- Nice design ✔️
- Correct GitFlow ✔️

I was a little concern about about loading the project it took more time then it supposed to.

Other than that Great job!
![GreatJobCharlieBrownGIF](https://user-images.githubusercontent.com/83097009/203809278-13c9bc7d-d12f-4eff-9c93-c43822f102f0.gif)
